routes/web.php
<?php

use App\Models\Produit;
use App\Models\Commande;
use Illuminate\Http\Response;
use App\Http\Livewire\MyResume;
use App\Models\CommandeProduit;
use App\Http\Livewire\WelcomePage;
use App\Http\Livewire\WelcomeFancy;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\ClientQuoteRequestPage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    // Get products
    $produits = Produit::all();
    $produits_ajoutes = CommandeProduit::count();

    return view('produits', compact('produits', 'produits_ajoutes'));
});

Route::get('/ajouter/{id_produit}', function($id_produit){
    // Get products

    $produit = Produit::find($id_produit);

    if(!$produit){
        return redirect()->back();
    }

    $commande = Commande::create([
        'id_utilisateur' => 1,
        'total' => 0,
    ]);

    $produit_commande = CommandeProduit::create([
        'id_produit' => $produit->id,
        'id_commande' => $commande->id,
        'quantite' => 1,
        'montant' => $produit->price * 1,
    ]);

    $produits_ajoutes = CommandeProduit::count();

    $produits = Produit::all();
    return redirect()->back();
});


Route::any('{r}', function(){
    return view('placeholder');
})->where('r', '.*');


Route::resource('produits', App\Http\Controllers\ProduitController::class);

Route::resource('commandes', App\Http\Controllers\CommandeController::class);

Route::resource('commandeProduits', App\Http\Controllers\CommandeProduitController::class);

app/Models/CommandeProduit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;



/**
 * Class CommandeProduit
 * @package App\Models
 * @version October 11, 2021, 4:23 pm UTC
 *
 * @property unsignedBigInteger $id_commande
 * @property unsignedBigInteger $id_produit
 * @property integer $quantite
 * @property number $montant
 */
class CommandeProduit extends Model
{


    public $table = 'commande_produits';




    public $fillable = [
        'id_commande',
        'id_produit',
        'quantite',
        'montant'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'quantite' => 'integer',
        'montant' => 'double'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

     // relationships
    function produit(){
        return $this->belongsTo(Produit::class);
    }
    function commande(){
        return $this->belongsTo(Commande::class);
    }
}

app/Http/Controllers/CommandeProduitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCommandeProduitRequest;
use App\Http\Requests\UpdateCommandeProduitRequest;
use App\Repositories\CommandeProduitRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CommandeProduitController extends AppBaseController
{
    /** @var  CommandeProduitRepository */
    private $commandeProduitRepository;

    public function __construct(CommandeProduitRepository $commandeProduitRepo)
    {
        $this->commandeProduitRepository = $commandeProduitRepo;
    }

    /**
     * Display a listing of the CommandeProduit.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $commandeProduits = $this->commandeProduitRepository->all();

        return view('commande_produits.index')
            ->with('commandeProduits', $commandeProduits);
    }

    /**
     * Show the form for creating a new CommandeProduit.
     *
     * @return Response
     */
    public function create()
    {
        return view('commande_produits.create');
    }

    /**
     * Store a newly created CommandeProduit in storage.
     *
     * @param CreateCommandeProduitRequest $request
     *
     * @return Response
     */
    public function store(CreateCommandeProduitRequest $request)
    {
        $input = $request->all();

        $commandeProduit = $this->commandeProduitRepository->create($input);

        Flash::success('Commande Produit saved successfully.');

        return redirect(route('commandeProduits.index'));
    }

    /**
     * Display the specified CommandeProduit.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $commandeProduit = $this->commandeProduitRepository->find($id);

        if (empty($commandeProduit)) {
            Flash::error('Commande Produit not found');

            return redirect(route('commandeProduits.index'));
        }

        return view('commande_produits.show')->with('commandeProduit', $commandeProduit);
    }

    /**
     * Show the form for editing the specified CommandeProduit.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $commandeProduit = $this->commandeProduitRepository->find($id);

        if (empty($commandeProduit)) {
            Flash::error('Commande Produit not found');

            return redirect(route('commandeProduits.index'));
        }

        return view('commande_produits.edit')->with('commandeProduit', $commandeProduit);
    }

    /**
     * Update the specified CommandeProduit in storage.
     *
     * @param int $id
     * @param UpdateCommandeProduitRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCommandeProduitRequest $request)
    {
        $commandeProduit = $this->commandeProduitRepository->find($id);

        if (empty($commandeProduit)) {
            Flash::error('Commande Produit not found');

            return redirect(route('commandeProduits.index'));
        }

        $commandeProduit = $this->commandeProduitRepository->update($request->all(), $id);

        Flash::success('Commande Produit updated successfully.');

        return redirect(route('commandeProduits.index'));
    }

    /**
     * Remove the specified CommandeProduit from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $commandeProduit = $this->commandeProduitRepository->find($id);

        if (empty($commandeProduit)) {
            Flash::error('Commande Produit not found');

            return redirect(route('commandeProduits.index'));
        }

        $this->commandeProduitRepository->delete($id);

        Flash::success('Commande Produit deleted successfully.');

        return redirect(route('commandeProduits.index'));
    }
}

resources/views/commande_produits/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Commande Produit</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'commandeProduits.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('commande_produits.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('commandeProduits.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/commande_produits/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Commande Produit</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($commandeProduit, ['route' => ['commandeProduits.update', $commandeProduit->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('commande_produits.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('commandeProduits.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/commande_produits/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Commande Produits</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('commandeProduits.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('commande_produits.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/commande_produits/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Commande Produit Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('commandeProduits.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('commande_produits.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/commande_produits/show_fields.blade.php
<!-- Id Commande Field -->
<div class="col-sm-12">
    {!! Form::label('id_commande', 'Id Commande:') !!}
    <p>{{ $commandeProduit->id_commande }}</p>
</div>

<!-- Id Produit Field -->
<div class="col-sm-12">
    {!! Form::label('id_produit', 'Id Produit:') !!}
    <p>{{ $commandeProduit->id_produit }}</p>
</div>

<!-- Quantite Field -->
<div class="col-sm-12">
    {!! Form::label('quantite', 'Quantite:') !!}
    <p>{{ $commandeProduit->quantite }}</p>
</div>

<!-- Montant Field -->
<div class="col-sm-12">
    {!! Form::label('montant', 'Montant:') !!}
    <p>{{ $commandeProduit->montant }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $commandeProduit->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $commandeProduit->updated_at }}</p>
</div>

resources/views/commande_produits/table.blade.php
<div class="table-responsive">
    <table class="table" id="commandeProduits-table">
        <thead>
            <tr>
                <th>Id Commande</th>
        <th>Id Produit</th>
        <th>Quantite</th>
        <th>Montant</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($commandeProduits as $commandeProduit)
            <tr>
                <td>{{ $commandeProduit->id_commande }}</td>
            <td>{{ $commandeProduit->id_produit }}</td>
            <td>{{ $commandeProduit->quantite }}</td>
            <td>{{ $commandeProduit->montant }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['commandeProduits.destroy', $commandeProduit->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('commandeProduits.show', [$commandeProduit->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('commandeProduits.edit', [$commandeProduit->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>